### ISSUE TITLE
What kind of bots  are supported on linux?

### ISSUE THREAD

**Issue by livello** [kondrak/vkQuake2#103]
I tried crbot, gladiator, 3zb2re but no luck.

**Comment by kondrak** [comment]
What exactly is the problem? I only focused on renderer here, so not sure what exactly those bots may require.

**Comment by gribbs88** [comment]
Try:

https://github.com/DirtBagXon/3zb2-zigflag 

or 

https://github.com/yquake2/3zb2

They may work with this Vulkan 3.21 as well. I  am not sure.

**Comment by livello** [comment]
I tried both bots 3zb2 and 3zb2-zigflag. 
![изображение](https://user-images.githubusercontent.com/15374538/89710894-771a8980-d98f-11ea-9cf8-049e98c9724d.png)
![изображение](https://user-images.githubusercontent.com/15374538/89710896-826db500-d98f-11ea-8f7c-838f6dda3d6c.png)

**Comment by kondrak** [comment]
I just tried 3zb2-zigflag and it seems to work perfectly fine:
![zigbot](https://user-images.githubusercontent.com/423295/89716585-7f35f180-d9ae-11ea-914d-54ea351ad58e.png)

One thing to consider here is that Linux build is 64bit only, so if the bot supplies/builds a `game.so` or `gamex86.so` file, it should be later renamed to `gamex64.so`. Otherwise, vkQuake2 won't be able to locate it and will just default to loading what it finds in baseq2 folder.

I hope it helps.

**Comment by livello** [comment]
Thank @kondrak you. Work like a charm!
