### ISSUE TITLE
Exclusive Fullscreen doesn't work

### ISSUE THREAD

**Issue by Lrflx** [kondrak/vkQuake2#111]
Hi,

When I try to put the game into exclusive fullscreen it reverts back and shows in console:

vkQuake2 v1.5.3
------------------------------------
Vulkan API: 1.2
Header version: 141
Devices found:
   #0: GeForce GTX 1080 Ti
Using device #0:
   deviceName: GeForce GTX 1080 Ti
   resolution: 3840x2160 fullscreen (MSAAx8)
   driverVersion: 452.6.0 (0x71018000)
   apiVersion: 1.2.133
   deviceID: 6918
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_MAILBOX_KHR
Swapchain image format: 44
Swapchain image count: 3
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_MAILBOX_KHR VK_PRESENT_MODE_IMMEDIATE_KHR
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface VK_KHR_get_surface_capabilities2 VK_KHR_get_physical_device_properties2 VK_EXT_full_screen_exclusive
Enabled layers:
Fullscreen Exclusive Mode acquisition error: VK_ERROR_INITIALIZATION_FAILED - reverting to borderless windowed mode.
QVk_EndFrame(): received VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT after vkQueuePresentKHR - attempting to reacquire in next frame.
Shutting down Vulkan

Please tell me if there is any other info I may provide

**Comment by kondrak** [comment]
Hi!
It seems the application is unable to initialize fullscreen exclusive mode on your system for some reason, so instead of crashing it just reverts to default borderless window. This could be caused by numerous factors - things like driver bug, some GPU vendor specific overlays running in the background, some other software installed on the system or even the way fullscreen mode is handled by the application itself. I'm unable to reproduce this on any system I own, so I can't pinpoint the exact cause of this.

**Comment by Lrflx** [comment]
Btw, eventually I tested it a bit more and it seems exclusive fullscreen will work, but only with vsync enabled ingame, with it disabled it always falls back to borderless, maybe it's a vulkan thing, don't know for sure

**Comment by kondrak** [comment]
It's the driver's role to decide whether FS exclusive will be enabled or not, like I said - a number of factors can be involved and it's not guaranteed that it will work every time.
