### ISSUE TITLE
Disable 2D Texture Filtering (HUD, Menu GFX, etc.)

### ISSUE THREAD

**Issue by OpenRift412** [kondrak/vkQuake2#142]
Could we get an option to turn off the texture filtering that's specifically applied to HUD and menu elements? I think these were designed without the filtering in mind, as in the vanilla game, they aren't filtered at all.

**Comment by kondrak** [comment]
Are you sure about the vanilla game? I just checked and all textures are filtered the same way, I even compared output images between OpenGL and Vulkan and both cases apply linear filtering. Still, this shouldn't be too difficult to implement, so I guess I could add a toggle.

**Comment by OpenRift412** [comment]
> Are you sure about the vanilla game? I just checked and all textures are filtered the same way, I even compared output images between OpenGL and Vulkan and both cases apply linear filtering. Still, this shouldn't be too difficult to implement, so I guess I could add a toggle.

I just checked my vanilla 3.20 .exe in several resolutions in GL mode, and the only thing that is filtered is the console background.

**Comment by kondrak** [comment]
So I looked at this again with a fresh mind and honestly - no idea where the differences come from :) I screen capped the "vanilla" Quake 2 HUD in OpenGL and compared it against what vkQuake2 outputs in Vulkan - the images are exactly the same. 
As for the quit screen image - yeah, not looking the prettiest but it's also part of preserving original behaviour of the game, so it's not something that's going to be addressed, either.

![hud](https://github.com/kondrak/vkQuake2/assets/423295/c9aa7e1e-5461-4420-8857-363976f59f67)

I'll close this issue, since the project is already complete feature-wise and I don't really spend more time than needed on it (bug-fixing, testing new Vulkan features, minor tweaks etc.).

**Comment by Slider-Whistle** [comment]
Great work, sounds like I was pretty lucky to get that tiny no-music thing to get implemented
