### ISSUE TITLE
custom resolution not applying

### ISSUE THREAD

**Issue by suLac4ever** [kondrak/vkQuake2#166]
I tried vkquake2 on my Steam Deck via GE-Proton 8.25 on the latest version of SteamOS 3.5.7
It did run without any issues but the native resolution of the deck isn't available from the graphics options menu in vkquake2. Because of this I tried setting a custom resolution via the base cfg and autoexec cfg:
```
set r_customwidth 800
set r_customheight 500
set vk_mode -1
```
Before it ran in 640x480 in borderless windowed mode with the FSR scaling to fill the screen, which looks and runs very well except for the black bars because of the 4:3 aspect ratio. To get rid of the latter but still save power by using a lower resolution I wanted to try the resolution above, which scales very nicely to the Decks full resolution via FSR with many other games given its also 16:10.

But It refuses to use that but instead jumps back to one of the standard 4:3 resolutions.

Did I missing something I also have to set in the cfg to get it to work or is there a different 16:10 resolution you know to work or do they not work all together?

Anything you would advise me to try?

**Comment by kondrak** [comment]
Hi! Thanks for your patience - I don't really look here that often anymore due to other responsibilities these days.

Out of curiosity, if you set the custom resolution using the native Steam Deck resolution - does it work and load fine for you?
The issue you're experiencing is caused because for some reason 800x500 cannot be loaded - usually by that particular resolution not being supported on the given OS/driver (you can also trigger this on Windows if you try and set some weird/quirky screen resolutions like in your example). I don't own a Steam Deck so I can't verify this is the exact cause, so I'm afraid I can't help out much otherwise.

But really nice to hear that vkQuake2 actually works there just fine!

**Comment by suLac4ever** [comment]
Thank you for taking the time to respond to this despite of being occupied otherwise! Means a great deal to me :)

I tried it out and setting the custom resolution to the Steam Decks native 1280 x 800 just resets it to the last used working resolution (in my case vid mode 2).

This being a driver level problem seems weird, because 800 x 500 also works without any problems for other games but if I recall correctly all of the are not Vulkan games but use older API as DX9 or OpenGL. So maybe it's a Vulkan problem or a Proton-Vulkan problem ...

Anyway, I hope you are doing well and thank you again for taking the time ... blessings to you!

**Comment by kondrak** [comment]
The "resolution not supported" is at this point only a guess, since that's what I ran into before - this might as well be a valid issue with current context creation and window handling code also, since it's over 20 years old and doesn't take into account the developments that happened afterwards.
If I ever get my hands on a Steam Deck, I'll definitely check it out and see what's happening under the hood! :)
