### ISSUE TITLE
“Could’t load maps/base1.bsp” when rewriting original game files with vkQuake2 prebuilt package files

### ISSUE THREAD

**Issue by Marat-Tanalin** [kondrak/vkQuake2#75]
The current vkQuake2-installation procedure is somewhat confusing. It’s apparently needed to first unpack a vkQuake2 prebuilt package into an _empty_ directory, then copy the original `*.pak` files from the full Quake 2 version into the vkQuake2 unpacked directory.

But the typical installation sequence (working e.g. in case of Yamagi Quake 2 and Quake2xp) is the contrary: first the original game is installed (e.g. downloaded via Steam), _then_ vkQuake2 (considered as a _patch_) is unpacked into that directory with _overwriting_ the existing files. But in that case, when trying to begin playing (after selecting a difficulty level and pressing the `Enter` key a couple of times), the game stops with the following errors output to the game console shown forcedly:

    ERROR: Could’t load maps/base1.bsp
    ShutdownGame

It took a while for me to figure out what happens, and it’s possible I’m not alone. So it would probably make sense to make vkQuake2 work when using the patch-type installation steps — probably by removing the demo-version files from the prebuilt vkQuake2 packages. Thanks.

**Comment by kondrak** [comment]
By design, vkQuake2 is meant to work as a standalone application and I want to keep it that way. The readme contains specific instructions on how to get the game running with retail packs, so it should be clear enough. However, I can see where you're coming from so I added a note on overwriting existing installation on Windows - something I never like doing myself since I hate interfering with original software.

**Comment by Marat-Tanalin** [comment]
> By design, vkQuake2 is meant to work as a standalone application and I want to keep it that way.

Understood, the idea of standaloneness perfectly makes sense.

We could still probably make the error message more informative and helpful. So instead of the current:

> ERROR: Could’t load maps/base1.bsp

the message could be something like this:

> ERROR: Could’t load maps/base1.bsp
> Make sure you did not overwrite the original game files with the vkQuake2 files.
> Instead, unpack the vkQuake2 package into an EMPTY folder, then copy the original *.pak files into the vkQuake2 folder.

This would greatly help newcomers to quickly figure out what’s happening and would also make vkQuake2 even more standalone.

**Comment by mjr4077au** [comment]
@kondrak just wanted to add some commentary to this from my observation.

Typically with source ports, when I get a new release, I just unzip the new version over the top. Because the demo files are included, when you go "yes to all" when extracting, you end up overwriting the retail PAK files, and I've been caught out twice.

I wonder whether it's best to include the pak0.pak file in a "baseq2" zip file that can be extracted if the user wishes to play with demo content. The only other thing would be some kind of installer, but I think that adds much more complication.

**Comment by thesyndrome43** [comment]
I am having the exact same issue and I followed your instructions exactly as written in the readme section of github:
I created a new folder for vkquake 2
I extracted all .pak files as well as the Video and Models folders from my steam copy of quake 2 into the vkquake2-1.5.8_win64\baseq2 directory
I run the game
it gives me a "couldn't load maps/base1.bsp" error and won't run

what am I doing wrong? I'm not used to this kind of modding
![vkquake2 readme](https://user-images.githubusercontent.com/110982576/183899153-80b42939-3819-499d-a9e1-25620a931ef8.jpg)
![vkquake 2 error](https://user-images.githubusercontent.com/110982576/183899155-46e2dd17-581b-455a-b9d1-273dacad0ef6.jpg)
g
