### ISSUE TITLE
Garbled text in output

### ISSUE THREAD

**Issue by tomgreen66** [kondrak/vkQuake2#78]
Having uninstalled Xcode (mainly to save some space) I found I needed to develop a Makefile to build Quake2 along the lines on the Linux method (rather than use xcodebuild).  Now have a working Makefile if others find it useful.  Noticed during the development that in `Vk_Strings_f` https://github.com/kondrak/vkQuake2/blob/576d48bbe8502c4a437ae1c884b9d4a87d569c39/ref_vk/vk_rmisc.c#L180-L182:

Not sure if the for loop is required - seems to be adding a constant to a string and creating garbage string in the output.

**Comment by kondrak** [comment]
This loop is used to change the version string's color to green - the garbage you see in the output is the side effect of this, since the game font doesn't map green characters to proper ASCII codes for letters/numbers. 

PRs are always welcome, especially if they're useful, so I'm open to a new Makefile that doesn't require XCode on MacOS!
